apiVersion: v1
kind: Pod
metadata:
  name: stateful-http-server
  labels: 
    app: http-server
spec:
  volumes:
    - name: hello-storage
      persistentVolumeClaim:
        claimName: ebs-pvc
  containers:
  - name: http-server
    image: yancanmao/app-stateful
    volumeMounts:
    - mountPath: "/data"
      name: hello-storage
