apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-http-server
spec:
  serviceName: "stateful-http"
  replicas: 3
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: yancanmao/app-stateful
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/data"
          name: hello-storage
  volumeClaimTemplates:
  - metadata:
      name: hello-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
